AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Description: >
  Excel Documents Extraction Lambda. PLEASE USE A UNIQUE STACK NAME IF YOU ARE ALREADY RUNNING THIS TEMPLATE. This template will create the AWS Lambda Function and associated Role.
Resources:
  LambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: WriteCloudWatchLogsLocal
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "aidemos-document-extraction"
        S3Key: "Excel-Extraction-Function.zip"
      FunctionName: !Sub 'AIDemos-DocumentExtraction-${AWS::StackName}-Excel-Function'
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaFunctionExecutionRole.Arn
      Runtime: python3.8
      Timeout: 60